### ISSUE TITLE
New Token missing when loaded with the same mnemonics from previous wallet

### ISSUE THREAD

**Issue by idoor88** [fmsouza/ethereum-wallet#5]
I created the first wallet with one row listed for the overview page, so I then clicked the plus button on the left top corner , which then asked me new wallet name, then I typed a new name, clicked next, after that it asked me to load the old wallet or create a new one, I selected Yes, load it, then I typed my old mnemonic, after that, I clicked opened wallet,  that will lead to load my old wallet, and the new wallet flashed in a short time and only the old wallet is displayed in the overview page.
So:
   1.  This wallet app can contain many wallets, each wallet can only contain one ETH token?
   2.  Can I have just one wallet with one single mnemonic or private key, and the single wallet can have many different tokens?
  3. the top left corner PLUS button means to add a new wallet, so how to add a new token?

Thanks 
idoor

**Comment by fmsouza** [comment]
Hello @idoor88,

Yes. You can add multiple wallets, which means you can add your private keys for several different Ethereum wallets. However, it does not support any ERC20 tokens as of now. It's something on the roadmap, but is not implemented yet.

Each ERC20 token is ruled by it's smart contract, and none of it's operations are standardized from one contract to the other, so there's no _easy_ way to implement support with an _one size fits all_ solution.

That's why you can't see your tokens in this wallet right now.

**Comment by idoor88** [comment]
Ok, got it, thanks for your guys' great work.
