### ISSUE TITLE
After Erase All Data in Settings, two wallets still show up

### ISSUE THREAD

**Issue by idoor88** [fmsouza/ethereum-wallet#6]
I have created two wallets, but I want to remove all of them since I want to start over again, but after I clicked Erase all data in Settings,  the two wallets are removed from the list in Overview page, but when I reload the page via command R(on mac), even I rebuilt and re-ran the ios simulator, the two wallets still show up, so how do I remove them completely? so where this two wallets are saved on my hard drive, which file should I remove from the hard drive?

Thanks
idoor

**Comment by fmsouza** [comment]
@idoor88 I believe the problem is due to the fact that the [removeWallet action](https://github.com/fmsouza/ethereum-wallet/blob/master/src/common/actions/wallets.js#L26) is only removing the wallets from the memory store, so it's not cleaning it from the [native storage](https://github.com/fmsouza/ethereum-wallet/blob/master/src/common/services/storage.js) as that's why it shows up again when you reload the app.

**Comment by fmsouza** [comment]
Yes, indeed. This is enough. It's just lacking this implementation right now because I was always pushing the changes with tests to guarantee every single change would be working less prone to fail as possible.

If you like the idea, you could PR this change to this project and I'd be glad to review and merge it.
